<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="WebApplication1/**/*.cs" />
    <Compile Remove="WebApplication2/**/*.cs" />
    <Content Remove="WebApplication1/**" />
    <Content Remove="WebApplication2/**" />
    <None Remove="WebApplication1/**" />
    <None Remove="WebApplication2/**" />
    <RazorComponent Remove="WebApplication1/**" />
    <RazorComponent Remove="WebApplication2/**" />
  </ItemGroup>

</Project>
